language: rust
rust: nightly
cache: cargo
sudo: false

matrix:
  include:
    - env: FEATURES=""
      rust: stable
      os: linux
    - env: FEATURES=""
      rust: nightly
      os: linux
  allow_failures:
    - rust: nightly

script:
  - cargo build
  - cargo test

after_success:
  - |
    echo "SUCCESS"
